### ISSUE TITLE
Feature Request: Add accounting for abandonment

### ISSUE THREAD

**Issue by oren0e** [phubers/erlang#6]
I was wondering if you could incorporate Erlang-A into the function that calculates the number of agents needed for SL. I'm trying to figure myself how to do it, but I guess you'll be faster.

Thanks.

**Comment by phubers** [comment]
I did put this on the To Do list about a year ago, but simply haven't gotten around to it yet, also because I did not find any implementations that could serve as inspiration.

It remains a To Do with no deadline for now. You are, of course, most welcome to implement this yourself and send me a pull request.
